### PR TITLE
Renamed the "kl" -> "ui"

### PR DESCRIPTION
**Pull request by matiastamsi**
## Renamed the "kl" -> "ui"

We have to make a pull request from one of the miniprojects at week 6. So, I refactored the userinterface parameter "kl" to "ui".

### CODE REVIEW

**Review by lambdakilo — APPROVED** [review]
tests are passing so this refactoring doesn't seem to break anything we know

**Comment by lambdakilo** [comment]
Also in this project we have the convention of
1. Programmer 1 creates the PR
2. Programmer 2 approves the CI passed PR
3. Programmer 1(@matiastamsi ) merges the PR

that being said feel free to merge your PR whenever you feel like it

**Comment by matiastamsi** [comment]
Hey,
I wonder if I just don't know how to merge this for your repo but instead of the merge button I have a line  "Only those with write access to this repository can merge pull requests". I wonder can I have the permission or have you any ideas?
Sorry for the extra trouble!

**Comment by lambdakilo** [comment]
> Hey,
> I wonder if I just don't know how to merge this for your repo but instead of the merge button I have a line "Only those with write access to this repository can merge pull requests". I wonder can I have the permission or have you any ideas?
> Sorry for the extra trouble!

No worries for the extra trouble! It's good that this was brought up as the same problem would have persisted for other commiters too. Pretty sure the other [commit](https://github.com/akirataguchi115/lukuvinkkikirjasto/pull/63/commits/784b5336e30da71fcd9dfbe760098ac0deba44fa) was meant to trigger the write acces enablation to the repo but that seemed to have failed.

Merging this commit manually due to an exception in the convention.

**Pull request merged**
